server:
  port: 1004

spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: 1111
